### PR TITLE
update: README.md PHP & Laminas

### PR DESCRIPTION
**Pull request by JediKev**
This updates the `README.md` file to include the newly supported PHP 8.2 as well as an update to add more verbiage to supported MySQL versions. This also adds credit to `laminas-mail` in the OS projects listings.

### CODE REVIEW

**Comment by JediKev** [comment]
Need to rebase for 1.17.x

**Comment by gerundt** [comment]
When you anyway touch the `README.md` maybe remove the very old  *Upgrading from v1.6* section like I did in the PR #6365? ☺ @JediKev

**Comment by Tinnitus97** [comment]
Sorry for copying but I couldn't do it any other way can you copy my changes into your pull request ?

https://github.com/osTicket/osTicket/pull/6572

Updated Links:

  * [Font-Awesome](https://fontawesome.com)
  * [HTMLawed](https://www.bioinformatics.org/phplabware/internal_utilities/htmLawed)
  * [jQuery dropdown](http://labs.abeautifulsite.net/jquery-dropdown) (Project deleted)
  * [jsTimezoneDetect](https://pellepim.bitbucket.org/jstz)
  * [laminas-mail](https://github.com/laminas/laminas-mail)
  * [mPDF](https://github.com/mpdf/mpdf)
  * [PasswordHash](https://www.openwall.com/phpass/)
  * [PEAR](https://pear.php.net/package/PEAR)
  * [PEAR/Auth_SASL](https://pear.php.net/package/Auth_SASL)
  * [PEAR/Mail](https://pear.php.net/package/mail)
  * [PEAR/Net_SMTP](https://pear.php.net/package/Net_SMTP)
  * [PEAR/Net_Socket](https://pear.php.net/package/Net_Socket)
  * [PEAR/Serivces_JSON](https://pear.php.net/package/Services_JSON)
  * [php-gettext](https://launchpad.net/php-gettext)
  * [phpseclib](https://phpseclib.sourceforge.net)
  * [Spyc](https://github.com/mustangostang/spyc)

**Comment by JediKev** [comment]
@Tinnitus97 

Your changes are now included in this pull request. Thanks again for the contribution.

Cheers.

**Comment by Tinnitus97** [comment]
Hello in Line 90 the JIPT site Link is down

**Comment by JediKev** [comment]
@Tinnitus97 

Yes, this is something we are planning on reviving soon. Please stay tuned!

Cheers.

**Comment by Tinnitus97** [comment]
okay Thanks

**Pull request merged**
