### PR TITLE
Fix localization links in README

### PR DESCRIPTION
**Pull request by mlocati**

### CODE REVIEW

**Comment by JediKev** [comment]
Needs to be rebased for 1.15.x

**Comment by mlocati** [comment]
> Needs to be rebased for 1.15.x

Done.

**Comment by JediKev** [comment]
@mlocati 

That created an additional commit which clouds commit history and is not necessary for rebasing. I'll rebase this for you.

Cheers.

**Comment by mlocati** [comment]
> That created an additional commit

Which one?

**Comment by JediKev** [comment]
@mlocati 

I see now, github was acting weird for a moment; I needed to fully refresh page. Looks good now!

Cheers.

**Review by JediKev — APPROVED** [review]

**Pull request merged**
