### PR TITLE
Time drop down update

### PR DESCRIPTION
**Pull request by jdelhome3578**

### CODE REVIEW

**Comment by ntozier** [comment]
Can you please post a screen shot of what this does where?

**Comment by jdelhome3578** [comment]
osticket time update

**Comment by ntozier** [comment]
Great thanks.  Thats what I thought you meant... but for a split second I thought, what if this is actually for a custom time field or something. :)

**Comment by jdelhome3578** [comment]
Another thought along with this would be a user preference setting to set a 12 hour and 24 hour format per user.

**Comment by greezybacon** [comment]
Could we preselect the value greater than but closest to the current time?

**Comment by jdelhome3578** [comment]
I don't see the need, I usually select times at the start, middle or end of my day so that doesn't make sense to me.

**Pull request closed without merging**
