### PR TITLE
redactor: Upgrade to version 3.4.0

### PR DESCRIPTION
**Pull request by JediKev**
This upgrades Redactor from `3.3.5` to `3.4.0` so that we are utilizing the latest code. This addresses a few security issues with upstream Redactor as well as provides a few bug fixes and improvements. This also updates Redactor's core plugins o ensure everything Redactor is fully up-to-date.

### CODE REVIEW

**Comment by TechCare-Aus** [comment]
@JediKev - very interested in this. How soon can we expect some of these changes to be merged into the main develop-next branch?

Do you know if this fixes these issues:
- If I paste a password that contains < in the beginning it hides it from view. I can see it in the code, but not in the HTML view.
- Also if I paste a link that contains & it only highlights part of the link, not the whole thing. See below.
- If I paste content copied from Word or OWA or similar it doesn't copy nicely. I have to SHIFT + CTRL + V to get it to abandon the formatting.
- Lastly in the above problem, even if I abandon formatting it still copies implementing 2 lines.

I did reach out to the redactor support, I believe you mentioned contacting them directly for support. But would you prefer a github issue?

**Comment by JediKev** [comment]
@TechCare-Aus

You’ll have to apply the changes and test those out to see. It’ll be merged very soon once we go through and review, test, approve the open pull requests. Also, this will be merged into the develop branch, we moved 1.14.x to develop and develop-next will be used for the next major release.

If it’s an issue with Redactor itself then contact Imperavi directly as they’ll be able to best handle it. You could create an issue here if you aren’t able to contact them.

Cheers.

**Comment by mlipok** [comment]
This update is messing up the feature of pasting screenshot

**Comment by JediKev** [comment]
@mlipok 

Yes, upstream Redactor noticed this and released a new update. This can be found here:
- #5577 

Cheers.

**Pull request closed without merging**
