### PR TITLE
Increase content width

### PR DESCRIPTION
**Pull request by RikkiMasters**
Increase the width of the application to 95%, a maximum of 1440px, and a minimum of 960px.

Before:
Screenshot 2021-06-10 at 14 45 05

After:
Screenshot 2021-06-10 at 14 42 27

The 2.0 redesign is in the works but it's still a long way off. This will save me and others from having to manually change it with each update until then.

### CODE REVIEW

**Comment by JediKev** [comment]
@RikkiMasters 

Thank you for the pull request. We are not accepting any UI changes like this until v2.0. People are welcome to apply your patch at their own leisure though.

Cheers.

**Comment by mlipok** [comment]
@RikkiMasters  could you try my prosposal/version ?
https://github.com/osTicket/osTicket/pull/5749

**Comment by RikkiMasters** [comment]
@mlipok I like your implementation but some pages need adjusting
image

**Comment by TechCare-Aus** [comment]
> Thank you for the pull request. We are not accepting any UI changes like this until v2.0. People are welcome to apply your patch at their own leisure though.

@JediKev - Is there a guesstimate on v2.0? 2021? 2022?

**Comment by JediKev** [comment]
@TechCare-Aus 

Not at this time. You can follow the progress on our roadmap here:
- https://github.com/osTicket/roadmap

Cheers.

**Comment by TechCare-Aus** [comment]
@JediKev 

Could only hope :) The roadmap is a brilliant move. But it hasn't been updated in 4 months :(

**Comment by JediKev** [comment]
@TechCare-Aus 

This is because we are still in the early stages and there is not much to update on yet. We created the roadmap initially as more of a base template that we will add on to. Basically figuring out how we are going to structure the roadmap, etc. Keep in mind we are still developing/updating legacy osTicket currently as well. Don't worry though, traction will soon pick up and the roadmap will be lighting up like Christmas.

Cheers.

**Comment by mlipok** [comment]
> @mlipok I like your implementation but some pages need adjusting
> image

pop up me in my:
https://github.com/osTicket/osTicket/pull/5749

**Comment by mlipok** [comment]
> @mlipok I like your implementation but some pages need adjusting
> image

As I said:
https://github.com/osTicket/osTicket/pull/5749#issuecomment-863107067

For recent change take a look to my:
https://github.com/mlipok/osTicket/blob/develop/scp/css/scp.css

btw.
Related:
https://github.com/osTicket/osTicket/pull/3165
https://github.com/osTicket/osTicket/issues/3166
https://github.com/osTicket/osTicket/pull/5749
https://github.com/osTicket/osTicket/pull/5909

**Comment by JediKev** [comment]
UI/UX changes coming as part of v2.0.

**Pull request closed without merging**
