### PR TITLE
redactor: Chrome Formatting Issues

### PR DESCRIPTION
**Pull request by JediKev**
This addresses issue #3849 where Redactor bold, italics, etc. does not work
properly on Chrome versions 58+.

### CODE REVIEW

**Comment by eltreno** [comment]
I tried this, but it didn't fix the issue, still won't allow highlighting, then formatting of single or multiple words.

Using Chrome Version 59.0.3071.115 (Official Build) (64-bit) 

Firefox as reported works fine.

Also on Chrome, it will do very random things like:
1. Highlight single word
2. Click Bold --> Nothing ( Inspecting dom shows new blank link inserted under sentence. )
3. Highlight whole sentence - single line only.
4. Click Bold --> (at random few words are bolded but not whole sentence) ( Inspecting dom shows new blank link inserted under sentence with strong tags added areour the few words and another blank new line inserted.)

**Comment by eltreno** [comment]
This fix does work!!!

Apologies for my previous POST, Cloudflare didn't remove old cached file without the version parameter on it - of course!

From my Testing in Chrome, this does in fact fix the wsywyg formatting issue in Chome where you cannot format individual or multiple words in osticket V1.10

**Comment by telx85** [comment]
This fix works for me as well. Thank you very much.

**Comment by telx85** [comment]
Can we please get this added to 1.10.1 (or 1.10.2 ??). Easy enough for me to just replace the file, but for others it can be mighty annoying.

**Comment by JediKev** [comment]
It can't be added to 1.10.1 because it's already packaged and released but it will be added to the next release coming out soon (v1.10.2, I think is what it will be called). Stay tuned!

**Comment by JediKev** [comment]
#4113 is more robust and replaces this. ☹️

**Pull request closed without merging**
