### PR TITLE
fix #3546

### LINKED ISSUE #3546: Valid CSRF Token Required  OsTicket 1.10
Hi, any help for this problem?
OsTicket 1.10
Win 2012 R2
Apache 2.4
Php 7.1
Installed everything, get this problem. Read a lot, found solution to change "session.auto_start" to 1 and it worked for me. I logged in, but after a while still get same problem.

### PR DESCRIPTION
**Pull request by kaorukobo**
DbSessionBackend->read() should not return null but empty string.

### CODE REVIEW

**Review by protich — APPROVED** [review]

**Review by PeopleInside — APPROVED** [review]

**Comment by doganzorlu** [comment]
PHP 7.1 and osticket, works with this fix...

**Comment by azimiiuc** [comment]
Thank you, it works for me.

**Comment by fralix** [comment]
Why is it not merged into latest release? I can't see any reason for it ...

**Comment by ntozier** [comment]
@fralix because this PR didn't exist when the last non-maintenance release happened.
1.10 was released on 01 Nov 2016.
This PR was made 30 Mar 2017.

**Comment by Peneheals** [comment]
It looks like this code exists in the current develop and 1.15.x branches:

https://github.com/osTicket/osTicket/blob/1.15.x/include/class.ostsession.php#L200
https://github.com/osTicket/osTicket/blob/develop/include/class.ostsession.php#L200

So it can be closed, or am I missing something?

**Comment by kaorukobo** [comment]
@Peneheals As far as I see the code at a glance, I think it is right. Expecting someone to reopen if needed, I close this.

**Pull request closed without merging**
