### PR TITLE
issue: Multiple File Display

### PR DESCRIPTION
**Pull request by JediKev**
This addresses an issue where FileUploadFields on the ticket header is not displaying all attachments in the field.

### CODE REVIEW

**Comment by protich** [comment]
I think testing for a positive (string in this case ) would be a better solution.

```php
if (is_string($v) && strlen($v) > 200)
  truncate... 

```

**Comment by JediKev** [comment]
@protich

When you do that, if you only have one file it’ll truncate the name and put an icon in a weird place. Basically, if it’s a file field then we should display the entire file name(s) or at least a list of longer truncated names with no icon. I’ll play with it a little more.

**Comment by protich** [comment]
My concern is `$a->getField() instanceof FileUploadField` - you're basically testing the last answer every time from foreach loop around line 600 - so if `FileUploadFiled` is in the middle of then the fix is mute!

I think the display format (e.g truncating or not) should go on display call - around line 601.

**Comment by protich** [comment]
Closed the PR by mistake -

**Comment by JediKev** [comment]
@protich 

Updated.

Cheers.

**Comment by protich** [comment]
@JediKev - Please rebase this PR on top of `develop-next`

**Comment by JediKev** [comment]
@protich Rebased.

**Pull request merged**
