### PR TITLE
Web Portal Fixes:

### PR DESCRIPTION
**Pull request by aydreeihn**
- Add space between column headers and sort arrow
- Fix sorting by 'Subject' column
- Fix redactor issues with 'Reset' button
	- Make sure text within redactor is cleared correctly
	- Make sure we don't keep attachments if Reset
- Make sure redactor is reinitialized where needed

This will fix the Reset button everywhere else as well as in the Web Portal.

### CODE REVIEW

**Comment by perryk** [comment]
Apologies if incorrect, it looks like some of this is replacing #3898.

One small part of #3898 looks to be covered in #4239 too.

Not any trouble, just making a note of this.

**Comment by JediKev** [comment]
@perryk

Yea there will be some merge conflicts and also I noticed an issue with `js/redactor-osticket.js` line `314` on this pull request. Every time you submit the page the text box is duplicated on the page making it look really weird.

Cheers.

**Comment by perryk** [comment]
Thanks for the details, I think I'll leave it in my testing instance for a bit and check it out a little further if I have a chance. 

Cheers.

**Comment by aydreeihn** [comment]
The code has now been updated so that it no longer duplicates the text box. Thanks for the input!

**Comment by perryk** [comment]
You're welcome, thanks for the update.

**Pull request merged**
