### PR TITLE
Merge tickets

### PR DESCRIPTION
**Pull request by Micke1101**
http://osticket.com/forum/discussion/89699/osticket-v1-10-merge-duplicate-ticket-mods-attached/p1
This modification was originally posted on the forum and since i've done some modifications to it myself.

Don't forget to add the permission to your role to test it out.

- [x] Merge/link together tickets.
- [x] See all merges/links in the relations tab under either a master or child ticket.
- [x] Delete the merge/link from either inside the master ticket or from the ticket list.
- [x] Duplicate button if you want to create a copy of an existing ticket.

My modifications
- [x] Merge/split event.
- [x] Copy the owners and collaborators from the child tickets into the master ticket. (configurable)
- [x] Search for tickets that you've access to that are open to make them a master ticket.
- [x] New merging tab under Admin panel -> Settings -> Tickets -> Merging
- [x] If a user tries to open a link to a child ticket they're the owner of they'll get redirected to the master ticket (configurable)
- [x] Users can't open a closed child ticket (configurable)
- [x] You can set what closed status you want your child tickets to get.
- [x] Display child ticket thread along with the master tickets thread. (configurable staff/client)
- [x] Deleting of tickets should clean up after itself.
- [x] Improve events.
- [x] Set defaults.
- [x] Fix duplicate issue when combining threads.
- [x] Translations.
- [x] Switch to ORM.

To do
- [ ] Check what happens if a user tries to reply to a permalocked child ticket by email.

### CODE REVIEW

**Comment by Micke1101** [comment]
image
image
image
image
image
image
image
image
image

**Comment by Micke1101** [comment]
Here you can see how it looks like when you have the combine thread setting active, have not added the events, only the entries, not sure if events in the child would be valid in the master.
image

**Comment by Micke1101** [comment]
Here you can see how it looks like when combining threads, not currently combining events as i see little gain in that, but perhaps it should be available.
image

**Comment by Micke1101** [comment]
Here you can see how it looks like when combining threads, not currently combining events as i see little gain in that, but perhaps it should be available.
image

**Comment by Micke1101** [comment]
Translations
'<b>{somebody}</b> merged this ticket with %s{data.id}%s<b>{data.child}</b>%s {timestamp}'
'<b>{somebody}</b> split this ticket from %s{data.id}%s<b>{data.child}</b>%s {timestamp}'
'Ticket selected for master cannot be one.'
'Ticket #%s cannot be a child.'
'Ticket #%s cannot be closed.'
'Select at least one viable ticket'
'Ticket #%s is not merged.'
'Merging settings.'
'On merge'
'Copy owner and collaborators'
'Combine thread'
'Staff page'
'Client page'
'Redirect'
'Child ticket'
'Child status'
'(disabled)'
'Permalock'
'Duplicate button'
'Available'
'Merging'
'Merge'
'Select a ticket'
'Duplicate'
'Relations'
'Date Merged'
'Split'
'to merge tickets'
'No master ticket'
'Unable to merge some of the tickets.'
'Ticket merged successfully'
'No ticket to split'
'Unable to split ticket.'
'Ticket split successfully'
'to duplicate tickets'
'Unable to duplicate ticket.'
'Ticket #%s duplicated into #%s successfully'
'Tickets merged successfully'
'Unable to split some of the tickets.'
'Tickets split successfully'
'MASTER'
'CHILD'

**Comment by snizzleorg** [comment]
this is great news!

**Comment by Micke1101** [comment]
- Yea haven't really touched the sql portion yet, except for adding the events so, as soon as i've had a look at the ORM stuff i'll try and change to that.
- Yea i've not put much time on the choises of words so if you see something that could do with a better option then please share.
- Altered the variablenames a bit, some still seem a bit off but hopefully will be better now.
- That's weird, I'll double check it then, i used regex to fetch them and then checked if they were already present in the translation files, but must have missed them then.

**Comment by Chefkeks** [comment]
Regarding the last point with the translation, I guess you got me wrong. When looking at the code I miss the php echo code with __('Translation phrases') inside the HTML parts since currently, if I am not mistaken, the phrases will be ignored by the osTicket translation system. I could be wrong but I don't think so - at least I hope so :D

**Comment by Micke1101** [comment]
Just checked all the translations and the ones that should have echo infront of them seem to do, the rest are either combined and later echod or passed to functions that handle the echo.

**Comment by burgiuk** [comment]
When can we expect this to be merged with the primary branch?

**Comment by ntozier** [comment]
@burgiuk no dev has ever said that it would be accepted, so I do not think that you will receive a reply to a question like this.

**Comment by alfie013** [comment]
Hi @Micke1101,

I tried to apply this merge function in our osTicket but it gives me an error to the Parent (500 Internal Error) when someone replied to CHILD Ticket. It seems that when the CHILD Ticket is reopened, the condition on Parent Ticket messed up which lead into an error. Hope you can help me fix this issue.

Regards,
Alfie

**Comment by Micke1101** [comment]
Hi @alfie013 

Do you have the php error log entries for when this happend?

**Comment by alfie013** [comment]
Hello @Micke1101,

Seems the PHP Error Log is not enabled in our Server.

Thank you,

**Comment by Micke1101** [comment]
Ok i'll see if i can get a similar enviroment setup.
Did you download the release and then applied the PR or did you download it from the fork?
Could you provide the settings that you have for merging?

**Comment by alfie013** [comment]
I just downloaded the release and applied the PR.

Here is the current settings for Merging Functions.


Merge settings.
On merge:	             ✓  Copy owner and collaborators  
Combine thread:	     ✕  Staff page  
                                     ✕  Client page  
Redirect:	                     ✓  Child ticket  

Permalock:	              ✕ Child ticket  
Duplicate button:	      ✕ Available  


Regards,
Alfie

**Comment by alfie013** [comment]
@Micke1101,

Thank you for your assistance. I deleted the settings-merging.inc.ph, however, I still got an error where I can't open the Parent ticket (500 Internal Error) if the Child ticket is open. 

BTW, if the Child Ticket is marked as Closed the Parent Ticket can now be open without any issue.

Regards,

**Comment by Micke1101** [comment]
@alfie013 
I'm unable to replicate this error that you seem to be having.
I don't have access to a server with IIS at the moment so i tested on a apache one.
image

On merge:	✓ Copy owner and collaborators
Combine thread:	✕ Staff page
✕ Client page
Redirect:	✓ Child ticket

Permalock:	✕ Child ticket
Duplicate button:	✕ Available

Use

1. User creates Ticket 1.
2. User creates Ticket 2.
3. Agent realise Ticket 2 is a duplicate and merges Ticket 2 into Ticket 1.
4. User wonders why Ticket 2 was merged and sends a reply on Ticket 2.
5. Ticket 2 is now reopened.

Is it at step 5 that you experience the error?

**Comment by alfie013** [comment]
@Micke1101,

If your Parent ticket on your sample is Ticket 1, then the error should be on Ticket 1 (500 Internal Error) because its Child ticket is reopened.

Thank you,

**Comment by Micke1101** [comment]
Can you provide a screenshot of the error?
Everything looks ok on my end

image

Have you ran the SQL file?

**Comment by alfie013** [comment]
@Micke1101,

Here is error from the Master Ticket.
image

Here is the screenshot of the Child Ticket
image

Thank you,

**Comment by Micke1101** [comment]
Can you try and replace include/staff/templates/thread-entries.tmpl.php with the original one from osTicket?

**Comment by alfie013** [comment]
@Micke1101,

Still the same, I still got an 500 Internal Error on the Parent Ticket.

Regards,

**Comment by alfie013** [comment]
@Micke1101,

BTW, I noticed that if the Child ticket is reopened via Email, the Parent Ticket will get an error but if the Child Ticket is reopened via osTicket, the Parent Ticket will normally work without any issues.

Hope this help us to solve the issue.

Regards,

**Comment by Micke1101** [comment]
@alfie013 

I just tested in our live enviroment by responding by email and there's no errors.

Without that php error log, i'm not sure we'll be able to find the cause.

Are you able to test with PHP 5.6 instead of 7.0?

**Comment by alfie013** [comment]
Hello @Micke1101,

I was able to enabled the PHP Log errors and here is what I've got:

Fatal error: Uncaught Error: Call to a member function getName() on null in C:\inetpub\wwwroot\osticket\include\staff\ticket-view.inc.php:883 Stack trace: #0 C:\inetpub\wwwroot\osticket\scp\tickets.php(572): require_once() #1 {main} thrown in C:\inetpub\wwwroot\osticket\include\staff\ticket-view.inc.php on line 883

Regards,

**Comment by Micke1101** [comment]
Hmm that's funny could you post the in C:\inetpub\wwwroot\osticket\include\staff\ticket-view.inc.php
that's on the lines 870-900?
If i compare the error message to the default file and the one in the pull request it doesn't make sense.

https://github.com/osTicket/osTicket/blob/develop/include/staff/ticket-view.inc.php#L883
https://github.com/Micke1101/osTicket/blob/Merge-Tickets/include/staff/ticket-view.inc.php#L883

**Comment by alfie013** [comment]
Hello @Micke1101,

Here is the code on C:\inetpub\wwwroot\osticket\include\staff\ticket-view.inc.php

`<?php if ( $ticket->isMaster() ): ?>
		<h3 style="color:black;"> Child Tickets </h3>
		<table class="list" border="0" cellspacing="1" cellpadding="2" width="940">
			<thead>
				<tr>
					<th width="7.4%"><?php echo __('Number'); ?></th>
					<th width="14.6%"><?php echo __('Date Merged'); ?></th>
					<th width="29.8%"><?php echo __('Subject'); ?></th>
					<th width="18.1%"><?php echo __('From'); ?></th>
					<th width="16%"><?php echo __('Closed By'); ?></th>
					<?php if ( $thisstaff->hasPerm(Ticket::PERM_MERGE, false)): ?>
						<th width="2%">
						</th>
					<?php endif; ?>
				</tr>
			 </thead>
			 <tbody>
				<?php
				$children = $ticket->getChildren();
				foreach ($children as $T) {
					?>
					<tr id="<?php echo $T->getId(); ?>">
						<td nowrap>
						  <a class="Icon <?php echo strtolower($T->getSource()); ?>Ticket preview"
							title="Preview Ticket"
							href="tickets.php?id=<?php echo $T->getId(); ?>"
							data-preview="#tickets/<?php echo $T->getId(); ?>/preview"
							><?php echo $T->getNumber(); ?></a></td>
						<td align="center" nowrap><?php echo Format::datetime($T->getDateMerged()) ?: $date_fallback; ?></td>
						<td><div style="max-width: 279px; max-height: 1.2em"
							class="link truncate"
							href="tickets.php?id=<?php echo $T->getId(); ?>"><?php echo $T->getSubject(); ?></div>
						</td>
						<td nowrap><div><span class="truncate"><?php echo Format::htmlchars($T->getDeptName()); ?></span></div></td>
						<td nowrap><div><span class="truncate"><?php echo Format::htmlchars($T->getStaff()->getName()); ?></span></div></td>
						<?php if ( $thisstaff->hasPerm(Ticket::PERM_MERGE, false)): ?>
							<td nowrap>
								<form action="tickets.php?id=<?= $ticket->getId() ?>" method="post" style="display: inline-block;">
									<?php csrf_token(); ?>
									<input type="hidden" name="a" value="merge_delete">
									<input type="hidden" name="tid" value="<?= $T->getId() ?>">
									<div data-toggle="tooltip" title=" <?php echo __('Disconnect Merge'); ?>" style="height: 26px;">
										<button type="submit" class="action-button">
											<i class="icon-trash"></i>
										</button>
									</div>
								</form>
							</td>
						<?php endif; ?>
					</tr>
					<?php } //end of foreach ?>
			</tbody>
		</table>
	<?php else: ?>
		<?php $master = $ticket->getMaster(); ?>
		<h3>Master ticket: </h3>
            <table border="0" cellspacing="" cellpadding="4" width="100%">
                <tbody>
				<tr>
                    <th width="100">Number:</th>
                    <td><a class="Icon <?php echo strtolower($master->getSource()); ?>Ticket preview"
							title="Preview Ticket"
							href="tickets.php?id=<?php echo $master->getId(); ?>"
							data-preview="#tickets/<?php echo $master->getId(); ?>/preview"
							><?php echo $master->getNumber(); ?></a>
					</td>
                </tr>
                <tr>
                    <th>Priority:</th>
                    <td><?php echo $master->getPriority(); ?></td>
                </tr>
                <tr>
                    <th>Department:</th>
                    <td><?php echo $master->getDeptName(); ?></td>
                </tr>
				<tr>
                    <th>Subject:</th>
                    <td><?php echo $master->getSubject(); ?></td>
                </tr>
                <tr>
                    <th>Merge Date:</th>
                    <td><?php echo $ticket->getDateMerged(); ?></td>
                </tr>
				</tbody>
			</table>
	<?php endif; ?>`

**Comment by Micke1101** [comment]
Hmm it looks like it's because there is no agent assigned to the ticket, i'll see if i can test this later.

**Comment by Micke1101** [comment]
@alfie013 
Could you try this: https://github.com/osTicket/osTicket/pull/3768/commits/a45527a7a1657dc1cb6f8e076ca5bfafbe8b72a5

**Comment by alfie013** [comment]
Great!!. Thanks @Micke1101, it works now. :) Appreciate your help here. Keep it up!.

**Comment by utilewebsites** [comment]
Hi Mick1101,

I been installing your osticket merge and found some little problems.
1.	When a client want to check their ticket status there was never ending  loop
2.	When a client check their ticket and this is merge. He not saw the merge ticket content
3.	We experienced a sort problem in the tickets three.

I have fixed these problems and add a little update file, maybe you can a look at this and add this to the code.
Grtz, Pascal

[osticket update merge 1.09-2017.zip](https://github.com/osTicket/osTicket/files/1269721/osticket.update.merge.1.09-2017.zip)

**Comment by Micke1101** [comment]
Hi @utilewebsites 
I've now commited the accesslink fix, thank you :), never use this in our business so had completely forgotten about it.

**Comment by mahathir83** [comment]
Hi,

I able to install the MOD. But unable to view below attachment. Please help!! 
I'm using OST v1.10

Thanks.

merge
merging

**Comment by MackieeE** [comment]
@Micke1101 Is this Pull-request at all on the Dev team's roadmap at all do you know? This is a great PR I must add!

**Comment by Micke1101** [comment]
@MackieeE I don't think this particular pull request is on the Dev team's roadmap, I'm not sure if I think the feature is on the roadmap but I'd like to believe it is due to the popular demand.

**Comment by ntozier** [comment]
Last I heard Ticket Merge was on the RoadMap, as it is one of the most requested features. I cannot tell you if this is the implementation that the dev team will go with however.

**Comment by the-binder** [comment]
Micke1101, are you planning to update the merging plugin to 1.11.x? I merged your changes to the latest dev version of 1.11.x and I am receiving the following error:

Fatal error: Class 'TicketModel' not found in C:\workspace\www\eservicedesk\esd\include\staff\ticket-view.inc.php on line 296

-Tom

**Comment by Micke1101** [comment]
@the-binder I'm currently waiting on the official release of the first RC of 1.11 and will see then if the feature is going to be built in or not, if not then i'll most likely have a look at reimplementing it, unfortunately due to the database changes required an upgrade will most likely break the events.

**Comment by the-binder** [comment]
@Micke1101 Thanks for your response, I've actually manually merged the files into the 1.11.x branch for development and they are working quite well so far.

**Comment by alfie013** [comment]
Hello @Micke1101,

After merging this to my 1.10.1 branch, I got an error below:
image

Can you please help me resolve it?

Here's my osTicket Information:

Server Information
osTicket Version ---------------------------  v1.10.1 (9ae093d) —  Up to date
Web Server Software ---------------------- Apache
MySQL Version ---------------------------- 5.6.35
PHP Version ------------------------------- 7.0.19

[Error.zip](https://github.com/osTicket/osTicket/files/2133336/Error.zip)

**Comment by Micke1101** [comment]
@alfie013 the merging project does not affect the files that are being referenced in those warnings and the section you’re viewing shouldn’t be affected by the modifications in the first place so i’m suspecting something else is wrong.
For starters i don’t think that they’ve officially said that osticket is ready for php 7.0.
If it’s a vanilla branch that you’ve merged that’s what i’d check first if you’ve other modifications merged, you’ll have to check those, but my bet is on the php version.

**Comment by alfie013** [comment]
Hello @Micke1101 

I have now downgraded my PHP version to 5.4. However, delete button and merging of tickets is not working. See screenshot below:

image

**Comment by nicoletta-maia** [comment]
> Check what happens if a user tries to reply to a permalocked child ticket by email.

A new ticket is created

**Comment by dmwhite823** [comment]
I'm commenting on this issue for two reasons:
# To subscribe and to let you know that as an administrator of an osTicket deployment, being unable to merge tickets is our number one most annoying issue. I'd love this feature to go into core.
# To see if there's anything that I can do to help, test or otherwise assist in getting this issue closed and having the code merged into the core software.

Thanks for your work on this!

**Comment by Mynty100** [comment]
Hi sorry been trying to work out for over an hour how to download and install this mod. Can someone give me step by step
1) Download link
2) what to copy/override
3) SQL import file? 

I saw the orginal posts of this on the osticket forum. when I download the SQL file it has no file type and or when I attempt to import the .gz file it errors out.
I'm using phpmyadmin.

Really love this feature to be in the core as the business I work for will then moved to this helpdesk.

Thanking you.

**Comment by ntozier** [comment]
a .gz is a gzip archive.  You would need to un-gzip it.  (This may reveal a .tar file, but I have never opened the file you are talking about)

on linux: gunzip filename.gz iirc
on windows you would need to get a 3rd party zip utility (I think) like 7zip.

**Comment by Mynty100** [comment]
Yeah i can open it i can unzip it but when you edit it with notepadqq (Linux notepad++) it looks just like tickets.php file and has not got any SQL formatted data in it. i created the ost_ticket_relations table. worked that out. go the original version of this copied over but then get loads of errors. 

Still looking for Step 1 and 2 to be explained. how do I download this revision? I see no github link or anything. Im running v1.10.1 and do not wish override me current installation completely. 

Thank you in advance. 

Will try and refresh install once I can download this version.

**Comment by Mynty100** [comment]
I have made it myself through copy/pasting the code into these listed files manually. So no stress. All tests seem to be working well. love to see this feature made into the core version of osTicket.
Cheers.

**Comment by djschoone** [comment]
> I'm commenting on this issue for two reasons:
> 
> 1. To subscribe and to let you know that as an administrator of an osTicket deployment, being unable to merge tickets is our number one most annoying issue. I'd love this feature to go into core.
> 2. To see if there's anything that I can do to help, test or otherwise assist in getting this issue closed and having the code merged into the core software.
> 
> Thanks for your work on this!

Same for me! Please get this in core.

**Comment by vollkommenIrrelevant** [comment]
I'm waiting since two years for getting a bug merged...

**Comment by vollkommenIrrelevant** [comment]
@ntozier I didn't write that **this** is a bug. I wrote something different.

The second point - this is open source, so the devs should publish this criteria and should not just ignore so much PR and people who are trying to help.

**Comment by ntozier** [comment]
You wrote this ^

> The second point - this is open source, so the devs should publish this criteria and should not just ignore so much PR and people who are trying to help.

That have stated as much many times here on github.  Which is the only way that I know that.

**Comment by vollkommenIrrelevant** [comment]
correct! And now - think about it ;-)

**Comment by ntozier** [comment]
[channels his best Mister Spock impersonation]  "Captain it would be illogical to merge a bug."

**Comment by Jazz7584** [comment]
> I'm waiting since two years for getting a bug merged...

Hi thats why we left osTicket and Switched to another Ticket system.
Too bad - osTicket was over 8 years our buddy in daily business, but this core feature was requested since the beginning. :(

**Comment by nsl-94** [comment]
Hello @Jazz7584...

Sorry to bother you, but we are also waiting for this feature for our working environment. This is a must for our support teams.
We have been waiting for a long time for this but still with no avail...

You said that you left osTicket and turned to another Ticket system. Is it possible to send me an info about wich one you choose? We are searching for other options as well, even though we' re only sad about this specific issue :(

Thank you
Nuno

**Comment by Jazz7584** [comment]
@nsl-94
After long decision, because we wanted to keep osTicket, we switched to datto Autotask.
It is a PSA Software (Ticket included) but it has so much more. It's not free, but really worth the money! We save a lot time because of good workflows and automation.

**Comment by nsl-94** [comment]
> 
> 
> @nsl-94
> 
> We have plans to develop and release a Ticket Merge feature in upcoming versions. We realize this is a highly requested feature and have plans to implement such feature in later versions. Please stay tuned.
> 
> Cheers.

@JediKev 

Thank you for your response.

We know... we've been waiting for this for some time now.

Do you think it will happen in a near future, like until summer? I can make everybody from my company wait until then, but after that I'm afraid it will be impossible...

Nuno

**Comment by nsl-94** [comment]
> 
> 
> @nsl-94
> After long decision, because we wanted to keep osTicket, we switched to datto Autotask.
> It is a PSA Software (Ticket included) but it has so much more. It's not free, but really worth the money! We save a lot time because of good workflows and automation.

@Jazz7584 

Thank you fot the reply.

I will be looking for it.

Thank you
Nuno

**Comment by si458** [comment]
Hi
its been 3 months past the last comment,
has this merge feature been added to osTicket yet?
or will it never get a merge feature?

**Comment by JediKev** [comment]
@si458

As you can see this has not been merged. We are not going to merge this pull as we are working on our own way of merging tickets. This feature will be available in future versions. Please stay tuned.

Cheers.

**Comment by si458** [comment]
@JediKev looking forward to it! cant wait! really desperate for it!
clients dont no how to reply to a ticket instead of just sending a new one 🤦‍♂️

**Comment by stanbellcom** [comment]
@JediKev 
sounds great, do you have any plan or ETA when that feature is going to be available?

**Comment by alexflex25** [comment]
@JediKev
I've been waiting for this feature for a long time, do you have any news about its integration?
I am ready to help you if needed.

**Pull request closed without merging**
