### PR TITLE
redactor: Upgrade and Fix Formatting

### PR DESCRIPTION
**Pull request by JediKev**
This upgrades Redactor to 10.2.3 and addresses minor formatting issues with Chrome and Firefox.

### CODE REVIEW

**Comment by JediKev** [comment]
Need some people to test this out for me on the latest pull from `develop-next`. See if you can still do everything redactor in osTicket.

**Comment by JtheBAB** [comment]
I tested with the latest develop-next and this pull request. Looks like everything is working (Chrome). Just one small thing:

When i select "Formatting" --> "Header 1" (or something else) and i write nothing happen. But when i select my text and select "Header 1" it is working. I never used this feature so i don't know if it is normal or not.

**Comment by JediKev** [comment]
@JtheBAB 

First off....

**THANK YOU FOR TESTING**!! 😀

Secondly, it never functioned like that previous so that's good!

Please keep testing and reporting (if you can)!

Cheers.

**Comment by JtheBAB** [comment]
@JediKev 

So far it is working fine. We are using develop-next with this pull request within our production. All our team members can do there daily jobs to make customers happy ;)

**Comment by JediKev** [comment]
Text alignment breaks with new redactor...gotta look into this.

**Comment by wgalafassijr** [comment]
how to apply the patch to fix the issue about copy/paste?

**Comment by peterson-dane** [comment]
I'm testing this on a just-updated 1.10.4, and, while some stuff is fixed, I'm still seeing a lot of the same issues that I'd reported in #3849. **Bold** and **Italic** are not working unless you select a whole paragraph (everything between two newlines) or start on a newline and select "backwards" up onto the previous line. The same is true of the **Change Font Family** formatting.

I've also tried out the fix from #4113 on 1.10.4. This older fix is what I had been using, with pretty good success, on the previous version of osTicket that I was running (1.10.2).

**Comment by JediKev** [comment]
@peterson-dane 

I believe we are moving away from redactor in `2.0`...so please stay tuned!

Cheers.

**Comment by aloostrom** [comment]
Just added this into 1.12.2 with PHP 7.1.9 and IIS7.5. Fixed the paste issue, so I can't complain too much. Will be testing with KB and a couple other cases and add any issues I stumble across. Alignment changes are still a little wonky, but I can make it work. I use this for work, so pasting straight from clipboard(greenshot) saves a ton of time. Looking forward to 2.0!

**Pull request closed without merging**
