### PR TITLE
Feature :: Let user upload their own account avatar

### PR DESCRIPTION
**Pull request by iHunt101**
Hi, can you put an option for users to upload their own image avatar on their account?
If the support system is one of the most used system as part of the company, maybe it`s good to make them feel it like a personal account by having this feature.

capture

### CODE REVIEW

**Comment by ntozier** [comment]
gravatar.com :)

**Comment by iHunt101** [comment]
gravatar is good. But it will be great if a user can upload a profile image. :)

**Comment by ntozier** [comment]
Thats the point... they can to gravatar.  And osTicket uses that image.

**Comment by markus4000** [comment]
Not everybody likes gravatar.com . And I understand that. I would
appreciate if there would be an option to upload a picture in osTicket it
self.

Am 22.12.2016 04:25 schrieb "ntozier" <notifications@github.com>:

**Comment by greezybacon** [comment]
I've submitted pull requests to the LDAP plugin to support the avatars in the LDAP backend (like Active Directory), if that would help

**Comment by iHunt101** [comment]
That would be great! @greezybacon

**Comment by Abraka** [comment]
> I've submitted pull requests to the LDAP plugin to support the avatars in the LDAP backend (like Active Directory), if that would help

Thats great, but still, option for uploading your image to osticket is a MUST basic feature!

**Pull request closed without merging**
