### PR TITLE
login: Introduce a more "professional" login backdrop

### PR DESCRIPTION
**Pull request by greezybacon**
screen shot 2015-08-25 at 3 20 48 pm

The brick wall has caught some negative press. Perhaps we could rotate something a bit less like you've reached the end of a narrow alley-way...

### CODE REVIEW

**Comment by Chefkeks** [comment]
Looks really really :+1:

Maybe adding an option inside the company/branding settings would make some agents/admins happy too ;) (Btw excluding myself/our agents from that suggestion since we're happy SSO users and never see the login page :D)

**Comment by ntozier** [comment]
Maybe I'm odd, but I liked the bricks.  The sunset is better though.
being able to specify a background should definitely be part of the theme engine / skinability feature of osTicket in the future.

**Comment by mfelber** [comment]
@ntozier You are not alone. I like the bricks too. But I have no problem with the new look. It is also "pretty" ;-)

**Comment by greezybacon** [comment]
I like the bricks too. The nice thing about this design is that it evades the `background-blend-mode` and `mix-blend-mode` CSS requirements of the bricks page, which is sketchily supported by various browsers

**Comment by Hannibal226** [comment]
Looks gr8 and I like the design! 
CHEERS!

**Comment by greezybacon** [comment]
Add a selection in the backend to allow a selection of the backdrop and add a boring gradient to the list

**Comment by greezybacon** [comment]
##### Backdrop is completely customizable now
screen shot 2016-03-19 at 9 23 31 pm
Image copyright (c) Apple

##### New settings page allows for management of backdrops
screen shot 2016-03-19 at 9 25 13 pm

Unfortunately, I punted at adding a standard, boring gradient. Does anyone have one handy without any copyright?

**Comment by Hannibal226** [comment]
@greezybacon 
I justed searched a few in style u already used.
On same page u can search for urself and u can see at the right the license.

All following 'free fpr commercial use':

- Architecture
   - https://pixabay.com/en/architecture-modern-building-facade-1048092/
   - https://pixabay.com/en/louvre-pyramid-paris-architecture-102840/

- Landscape/Sunset
   - https://pixabay.com/en/coastal-island-sun-mu-sea-fishing-1140035/
   - https://pixabay.com/en/bagan-myanmar-burma-travel-temple-1137015/
   - https://pixabay.com/en/nature-sunset-north-sea-holiday-984414/
   - https://pixabay.com/en/sunset-landscape-assam-india-169925/
   - https://pixabay.com/en/cloud-sky-yellow-radius-sunshine-143152/

- HDR
   - https://pixabay.com/en/hawaii-mountains-sky-clouds-valley-209956/
   - https://pixabay.com/en/japan-aso-somma-sea-of-clouds-449822/

**Comment by Chefkeks** [comment]
Personally I like the last one from HDR list (https://pixabay.com/en/japan-aso-somma-sea-of-clouds-449822/)

**Comment by shaftandspanner** [comment]
Are there any requirements for the custom backdrop? (image size, format etc)  I've uploaded an image OK but can't get it to display  despite the checkbox being selected in the admin console

**Comment by JediKev** [comment]
@shaftandspanner 

It explains all of this in the help tip next to "_Use a custom backdrop_":
screen shot 2018-09-13 at 10 37 27

Cheers.

**Pull request merged**
