### PR TITLE
issue: Strip Emoticons

### PR DESCRIPTION
**Pull request by JediKev**
This addresses an issue where emoticons/emojis cut off the remainder of the email when being added to a ticket thread.

### CODE REVIEW

**Comment by FG-Lars** [comment]
v1.11 still has this issue, which was released after this commit.

I'm new to this so I'm just asking, why this fix isn't included?

**Comment by FG-Lars** [comment]
Just had to revert to my backup files.

This fix also strips national characters like Æ Ø Å æ ø å (Norwegian)

**Comment by JediKev** [comment]
@FG-Lars 

Updated. It should not remove Norwegian, German, etc. word characters, only emojis.

Cheers.

**Comment by FG-Lars** [comment]
Yes, that worked! Thanks

I discovered that it strips more:

Typed in:
image

Result:
image

**Comment by FG-Lars** [comment]
The issue with the < character is still present in v1.12

image

image

**Comment by JediKev** [comment]
@FG-Lars 

Read/follow on this thread please:
https://github.com/osTicket/osTicket/issues/3791#issuecomment-500506685

Cheers.

**Comment by drmistral** [comment]
Hi, after moved to 1.12, a huge amount of "(empty)2 tickets were produced (and restored by hand :).
I've just found that the cause was in `strip_emoticons` that causes an (empty)-body tickets each time `preg_replace` returns null for an internal error. I've found this error is returned each time the text to be processed is not UTF-8, and this happens many times, at least in my case.

**Comment by JediKev** [comment]
@drmistral

Tested using v1.12 and Gmail and cannot replicate the same results:

**Email (Gmail)**
https://m.imgur.com/gallery/iG1jxEY

**Ticket In Helpdesk**
https://m.imgur.com/gallery/XZoAdT9

Cheers.

**Comment by j127** [comment]
Is anyone else still experiencing this problem? Emojis are cutting of the support tickets in 1.14.2 (installed after the Feb 28, 2020 date above). There are more details [here](https://forum.osticket.com/d/98579-bug-report-unicode-emoji-cut-off-the-rest-of-the-email). Our support tickets often have unicode flags [like this](https://pastebin.com/AaWRi9Ew) in them, and it deletes anything after the flag.

**Pull request merged**
