### PR TITLE
SLA with Business Hours

### PR DESCRIPTION
**Pull request by rayfoss**
* [ ] Add tests
* [ ] Add hour validation
* [ ] Add installation script from 1.10
* [ ] Bug fix with different db timezone making DateTime misbehave
* [ ] Better error behavior on calculator
* [ ] Add a screenshot tour for @Chefkeks

### CODE REVIEW

**Comment by Chefkeks** [comment]
@rayfoss
Guess you forgot a task in your list ;)
 - [ ] Add a screenshot tour

**Comment by philbertphotos** [comment]
Want to see how this looks .. is it ready for prime time? Screenshots please.

**Comment by vieckzand** [comment]
how to use this features? Can this features run on applications already running?

**Comment by boynickie** [comment]
I sincerely hope this get's implemented within OSticket..

**Comment by Douks08** [comment]
Maybe this can help you a bit : https://framapic.org/nY9BWYH0njvx/9MyKhADREV7s.JPG
It's a screenshot from our current helpdesk system (BMC Track-It!). We have to setup our working hours ("Début" > "Fin"), tick which days are working days (Dimanche, Lundi, ....) and we can set hollidays/non-working days.

The countdowns (used to send you an alert for old tickets) are not working when out of working days/hours and in hollidays

**Comment by juraganerka** [comment]
can we apply that from existing support?
i tried to fresh install but getting error like this.
"**core: Unknown or invalid schema signature (98ad7d550c26ac44340350912296e673 .. e116fd179f0aa159eff7b40692e1c64c)**"

**Comment by animixx** [comment]
hello, could you please include the model of the table business_hours?? since is not created by the script

define('BUSINESS_HOURS_TABLE', $prefix.'business_hours')

**Comment by vieckzand** [comment]
anyone success implement this features in OSTicket v.1.10? Thank's

**Comment by ciaoamigo** [comment]
BUSINESS_HOURS_TABLE ????

**Comment by jesusaristigueta** [comment]
This looks awesome, but there's a Instalation process? Following those instructions will create the BUSINESS_HOURS_TABLE ?

Thank you 🐱

**Pull request closed without merging**
