### PR TITLE
Use PageNate->showing() for Users and Orgs in SCP

### PR DESCRIPTION
**Pull request by gerundt**
While working with users I missed the information, how many users we have. So I added the `PageNate->showing()` output to the overview lists.

### CODE REVIEW

**Review by JediKev — APPROVED** [review]
Looks nice. Very simple and works as intended.

The only thing I'd suggest is to make the commit message more descriptive next time. Try following the flow of something like this:
- https://github.com/osTicket/osTicket/pull/5738/commits/fbf0c7d88967fd4a30730c9a7257bd08a1cb54e0

Basically the first line of the commit message is the Title, then a blank new line, then the description on a new line after that.

Cheers.

**Comment by gerundt** [comment]
Good that you like it. And I will try to write better commit messages! 🙈

**Comment by JediKev** [comment]
@gerundt 

It's not a big deal, it just helps us and others track things better in the commit history.

Cheers.

**Comment by mlipok** [comment]
@JediKev I see you approved these changes is that mean that it will be merged automaticaly with next release ?

**Comment by JediKev** [comment]
@mlipok 

Yes, these changes will be merged soon and will be included in the next releases.

Cheers.

**Pull request merged**
