### PR TITLE
Custom Ticket Statuses

### PR DESCRIPTION
**Pull request by protich**
Continuation of PR #1094

### CODE REVIEW

**Comment by Dorian-Grim** [comment]
I am confused. Wasn't this supposed to let users to create custom ticket statuses?
image

**Comment by ntozier** [comment]
@Dorian-Grim this is a Pull Request from 2014. It was merged with develop-next on Aug 22, 2014.
The feature [The ability to create custom ticket statuses] has been part of the project for over 2 years, starting with version 1.9.4 (which was released on Oct 27, 2014).  I perhaps if you have a question you should ask it on the forums.  If you have a bug that you can replicate then report it by opening an issue.

**Comment by Dorian-Grim** [comment]
Well I was on 1.10 and I couldn't or didn't know how to create custom statuses...

**Comment by ntozier** [comment]
If you have a question please ask it on the forums.
If you have a bug that you can replicate please report it by opening an issue.

**Pull request merged**
