### PR TITLE
issue: LDAP Multi-Instance Fatal Error

### PR DESCRIPTION
**Pull request by JediKev**
This addresses an issue where if you have more than one instance of LDAP plugin enabled and try to lookup a User it fails with a fatal error of `Object of class StaffLDAPAuthentication could not be converted to string`. This is due to using `array_unique()` which can't convert objects to strings. This updates the method and adds the `SORT_REGULAR` flag so that it can compare without converting objects to strings.

In addition this addresses an issue where we were using static ID for StaffLDAPAuthentication backend. We updated the plugin code to reflect the actual Backend ID but the current AJAX regex for this doesn’t match this format. This updates the AJAX regex to match the updated format.

### CODE REVIEW

**Comment by cmwg71** [comment]
Question: we have 1.18.1 patch 1 and still an issue with LDAP & Authentification using multiple instances. But it seems abit different than here described (if i need to open a separate issue please advise). 

Plugin is normally installed and activated. Instance A with domain1.com configured and tested, works fine. Add instance B domain2.com the ldap lookup for instance B fails, while instance A still works. LDAP settings confirmed and correct in both instances.

Recreated multiple times, everytime a second instance is added that second instance does not work. 

Additionally the error message (slightly altered for privacy reasons):

`LDAP-Search failed: LDAP_REFERRAL Parameters: Base: dc=intern, dc=domain, dc=de Filter: (&(objectCategory=person)(objectClass=user)(|(sAMAccountName=username*)(firstName=username*)(lastName=username*)(displayName=username*)(mail=username*))) Scope: sub`

the above error is only seen if two instances are active and the error only happens on the 2nd instance in the list, the first instance will always work properply

**Comment by JediKev** [comment]
@cmwg71 

What's the full error? It says failed but provides no reason for the failure.

Cheers.

**Comment by cmwg71** [comment]
> @cmwg71
> 
> What's the full error? It says failed but provides no reason for the failure.
> 
> Cheers.

if you tell me where to look for the error, i will happily post it.

**Comment by JediKev** [comment]
@cmwg71 

If your PHP error logs and web server error logs don’t show more detailed errors then it’d be best to look at your AD logs on the AD server. There are guides online that explain how to review the AD logs for your specific environment. You can even enable debug logs on the AD server to see if it can shed more light.

Cheers.

**Comment by cmwg71** [comment]
> @cmwg71
> 
> If your PHP error logs and web server error logs don’t show more detailed errors then it’d be best to look at your AD logs on the AD server. There are guides online that explain how to review the AD logs for your specific environment. You can even enable debug logs on the AD server to see if it can shed more light.
> 
> Cheers.

I will check the webserver side, since each LDAP login individually works fine, just when 2+ instances are active it doesn´t anymore, so it has to be webserver side

**Comment by cmwg71** [comment]
i have a root webserver with plesk, within the domain name in question and it´s logs, the error_log shows nothing. the other logs only show the typical web connection infos.

in the plesk-php81-fpm log (which is the php version used for the web instance) i can find this:

```
[06-Jul-2024 05:32:50] WARNING: [pool support.domain.de] child 21504 said into stderr: "PHP message: PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/vhosts/domain.de/support.domain.de/include/class.CLconf.php' (include_path='./:/var/www/vhosts/domain.de/support.domain.de/include/:/var/www/vhosts/domain.de/support.domain.de/include/pear/:phar:///var/www/vhosts/domain.de/support.domain.de/include/plugins/auth-ldap.phar/include') in /var/www/vhosts/domain.de/support.domain.de/scp/advReports/class.advReports.php:483"
[06-Jul-2024 05:32:50] WARNING: [pool support.domain.de] child 21504 said into stderr: "Stack trace:"
[06-Jul-2024 05:32:50] WARNING: [pool support.domain.de] child 21504 said into stderr: "#0 /var/www/vhosts/domain.de/support.domain.de/scp/advReports/class.advReports.php(501): advReports->getThreadEventsObj()"
[06-Jul-2024 05:32:50] WARNING: [pool support.domain.de] child 21504 said into stderr: "#1 /var/www/vhosts/domain.de/support.domain.de/scp/advReports/class.advReports.php(310): advReports->prepareEventPlotData()"
[06-Jul-2024 05:32:50] WARNING: [pool support.domain.de] child 21504 said into stderr: "#2 /var/www/vhosts/domain.de/support.domain.de/scp/advReports/advReports_activity_tab.inc.php(7): advReports->getEventTabularGroupData()"
[06-Jul-2024 05:32:50] WARNING: [pool support.domain.de] child 21504 said into stderr: "#3 /var/www/vhosts/domain.de/support.domain.de/scp/advReports/advReports_activity.inc.php(148): include('...')"
[06-Jul-2024 05:32:50] WARNING: [pool support.domain.de] child 21504 said into stderr: "#4 /var/www/vhosts/domain.de/support.domain.de/scp/advReports/a..."
```

otherwise i can only see an actual error within osticket the ldap search error i already posted. if you have another log i should check please do tell me.

**Comment by JediKev** [comment]
@cmwg71 

oh.. you didn’t mention you had mods installed. You should retest with a vanilla instance of osTicket with no mods installed and see if you have the same results.

Cheers.

**Comment by cmwg71** [comment]
this is osticket.de (german version) as to mods, it has plugins, i am not aware of mods (at least not from me)

as the single instance ldap auth works, why should anything else already in the system change the outcome when in the same plugin a 2nd instance is added? each instance (with the other deactivated) works.

**Comment by cmwg71** [comment]
i had in the past the original osTicket and had the exact same issue there as well

**Comment by JediKev** [comment]
@cmwg71 

Oh, then we can’t support you. You are using a completely different product. We are not affiliated with them in any way. You need to reach out to them directly. This is not the place for modded installations (nor entirely different products for that matter).

Cheers.

**Pull request merged**
