### PR TITLE
Fixed two typos

### PR DESCRIPTION
**Pull request by digdilem**
Spotted this issue today, so fixing a typo in two places: defaut -> default

image

### CODE REVIEW

**Comment by JediKev** [comment]
@digdilem 

Thank you for the pull request. Since this is an issue with `1.14.x` _and_ `develop` you would need to make your branch off of `1.14.x` and make the pull request to `1.14.x` (as the base). Also, I would suggest a more descriptive title and description like:
>issue: Default Sorting Typos
>
>This addresses an issue where two labels are mistyped (**Admin Panel > Settings > Tickets > Queues > click a Queue > Criteria** and **Agent Panel > Queues > click Personal Queue > click Config cogwheel > Edit > Settings**). This updates both occurrences of `Defaut Sorting` to the correct spelling of `Default Sorting`.

This gives us and others a better idea of what the commit changed when looking through the history.

Also, these changes can be consolidated into one commit instead of two separate commits as they accomplish the same goal.

**Note:**
You can close this a create a new pull request or I can close this and make one on your behalf (if you wanted).

Cheers.

**Comment by digdilem** [comment]
I must admit I am quite confused by osticket's versioning - I spent some time in the 1.17 repo which has not been updated for years, yet has no explanation that it's a dead version on the readme?

This issue exists in this codebase (as well?) so I thought this would be the appropriate place for future versions?

Probably best if you create another PR one for me in the correct place, and/or merge this into them. I didn't have much time and it seemed a quick fix rather than raising an issue.

**Comment by ntozier** [comment]
There is no 1.17 repo. (there is also no 1.16 repo.)  We're you maybe looking at the very old 1.7 repo that was discontinued years ago?

The current branch is 1.15.x.  Which is here:
https://github.com/osTicket/osTicket/tree/1.15.x

**Comment by digdilem** [comment]
Yes, I meant 1.7, sorry. (Although still confused why that branch is still
listed public if it's discontinued, google took me there to begin with, but
that's not important)

Although I am still very confused because I made my PR against 1.15.x at
the link you gave, so not sure why I should be making it against 1.14.x ?

The issue exists in 1.15.x and what I fixed.

I've not done many PRs before, so perfectly happy to accept I'm at fault
here, but I'm just confused.

**Comment by JediKev** [comment]
@digdilem 

With osTicket we actively support 2 series at a time. For example, at the moment we support v1.15.2 (the latest release of the `1.15.x` series) and v1.14.6 (the latest maintenance release of the `1.14.x` series). This gives people the option to do minor code upgrades while they plan to do a major upgrade with database changes. Some people simply want to wait a while before they upgrade to ensure the latest series is well tested but they still want the bug fixes and security patches in the meantime.

Since this typo is present in both series you would need to make the pull request against the `1.14.x` series branch. This way it will be merged into `1.14.x` and then into `1.15.x`/`develop`. Now, if this typo was only present in the `1.15.x` series you'd make the pull request to the `develop` branch (like you did here). `develop` is our development branch where we merge new features, new bug fixes, etc. and once it is stable we merge it into `1.15.x` and get it ready for the next release.

With all this being said, I'll make the pull request for you so you can see what I mean. 

Cheers.

**Comment by digdilem** [comment]
Thanks for the explanation, that does make sense. I hadn't appreciated changes to the older branch would be pulled into the new one.

**Comment by JediKev** [comment]
@digdilem 

Here is the updated pull request:
- https://github.com/osTicket/osTicket/pull/5884

It uses your changes and rebases it for `1.14.x`.

Cheers.

**Comment by protich** [comment]
Rebased PR #5884 merged.

**Pull request closed without merging**
