### PR TITLE
Selected type of FAQ category was not showing properly

### LINKED ISSUE #3169: [Bug] When viewing FAQ category detail, the proper type is not selected
When I select Featured as type for my FAQ category and save it, then when I go back, Public is selected for this FAQ category.

### PR DESCRIPTION
**Pull request by rbukovansky**
This should resolve #3169 

Reopened for osticket:develop branch per @greezybacon request.

### CODE REVIEW

**Comment by greezybacon** [comment]
Looks good. Thanks @rbukovansky

**Comment by rbukovansky** [comment]
You are welcome. It was just annoying... ;)

**Comment by rbukovansky** [comment]
BTW You will probably just might need to cherry-pick https://github.com/osTicket/osTicket/pull/3200/commits/f0e113ba30058ade57e95155113ccce157198298

I need to redo my branching strategy... ;)

**Comment by greezybacon** [comment]
Indeed I will. Thanks again

**Pull request merged**
