### PR TITLE
Task duedate format

### PR DESCRIPTION
**Pull request by JediKev**
Fixes missing due date on task create caused by invalid datetime format sent to db.

**Pending**
- [ ] Invalid timezone conversion

### CODE REVIEW

**Comment by jdelhome3578** [comment]
What about #3100

**Comment by JediKev** [comment]
@jdelhome3578 that one looks similar but I see they have added some extra stuff that wasn't necessary so this adds just what we need to fix the problem.

**Comment by protich** [comment]
Commit now part of PR #3438 - which addresses the pending item on this PR.

**Comment by edukondalugorla** [comment]
Task Due date is displaying but can't edit due date. How to edit task due date

**Pull request closed without merging**
