### PR TITLE
issue: Adds osTicket Favicons

### PR DESCRIPTION
**Pull request by JediKev**
This addresses issue #4112 where osTicket does not have a default favicon.
This adds favicon images and references to them in the Agent and
Client headers so they appear correctly.

### CODE REVIEW

**Comment by rossum** [comment]
It would be nice if setting a custom favicon was configurable in the UI, so changes would be persistent across upgrades.

Thanks for taking this step!

**Comment by JediKev** [comment]
@rossum 

>It would be nice if setting a custom favicon was configurable in the UI, so changes would be persistent across upgrades.

Yes, this would be cool, definitely. We hope to add this in future versions so please stay tuned!

Cheers.

**Comment by prathibhab** [comment]
favicon doesn't appear in upload/scp/login.php

Patch for resolving this is attached.

[staff-header.txt](https://github.com/osTicket/osTicket/files/2840130/staff-header.txt)

**Comment by JediKev** [comment]
@prathibhab 

No need for the patch but thanks for bringing this to our attention.

Cheers.

**Comment by JediKev** [comment]
for some reason this never closed 🤷‍♂

**Pull request closed without merging**
