### PR TITLE
redactor: Upgrade to version 3.4.8

### PR DESCRIPTION
**Pull request by JediKev**
This upgrades Redactor from 3.4.6 to 3.4.8 so that we are utilizing the latest code. This provides a few bug fixes and improvements.

### CODE REVIEW

**Comment by mlipok** [comment]
Is Redactor an external project which you use in yours project ?
Where I can read about changes (change log) which are provided with new redactor version ?

**Comment by JediKev** [comment]
@mlipok 

Yes, go to Imperavi's website for the changelog.

Cheers.

**Comment by mlipok** [comment]
You mean this:
imperavi (dot) com (forward slash) redactor (forward slash) log

**Comment by JediKev** [comment]
@mlipok ya

**Pull request merged**
