### PR TITLE
Use 95% of the screen real estate no more waste space on the side...

### PR DESCRIPTION
**Pull request by EIJason**
Small changes to use more screen space... a world of difference ;)

image

image

### CODE REVIEW

**Comment by mburamorde** [comment]
Attached I found an small problem. The Text Input Area starts at the "old" position.

image

**Comment by EIJason** [comment]
Yep you just have to add the redactor a line to the redactor css to fix that….

There is another pull request I logged for that…. ;)

Regards
Jason
Yep you just have to add the redactor a line to the redactor css to fix that….

There is another pull request I logged for that…. ;)

Regards
Jason 

Jason Kisogloo
IT Systems Specialist
@|from|department|@
Europe Incoming Ltd & Tradetrav Ltd - @|from|st|@

Direct No: +44 (0) 203 994 0446
Office No: +44 (0) 208 994 5001

Fax No: +44 (0) 208 994 5044
Skype ID: jasonkis
Email: jason@europeincoming.co.uk

Address: Unit 11-12 Turnham Green Terrace Mews, London, W4 1QU, England
      
Follow or like us on
Facebook https://www.facebook.com/europeincoming.co.uk?ref=hl
LinkedIn https://www.linkedin.com/authwall?trk=ripf&trkInfo=AQF8ahG9cSWaGwAAAWbkg8Gg5EtxVxyZ7qKU7HCVbfzF08n4m9ilv9tvaVH1ysXeH1-wVY0emz8BjcCcT7sX4VZ8X84vDvr8Nlt1s-VICM5vRp3uwBKswaP1PYitR-Apa7eWV5Q=&originalReferer=&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fin%2Feurope-incoming-136985156%2F
Instagram https://www.instagram.com/europeincoming/
Twitter https://twitter.com/europe_incoming

Europe Incoming Ltd is registered in England & Wales. Company number: 7053949.
Registered office: Charterhouse (Accountants) Ltd, 166 College Road, Middlesex, HA1 1RA
For our Terms & Conditions please visit www.europeincoming.com or www.fitbookings.com
For our Privacy Policy please visit www.europeincoming.com/privacy-policy/ 

Offices: England | France | Italy | Scotland | Switzerland | Scandinavia

www.europeincoming.com | www.fitbookings.com | www.micebookings.com


This E-mail is from Europe Incoming Ltd. The E-mail and any files transmitted with it are confidential and intended solely for the use of the individuals to which they are addressed. Any unauthorized dissemination or copying of this E-mail, and any use or disclosure of any attachments contained in it, is strictly prohibited and may be illegal. If you have received the E-mail in error please notify sales@europeincoming.co.uk or telephone +44 208 994 5001. Please do not copy or disclose its contents to any person or body, and delete it from your computer systems. Europe Incoming Ltd recommends that this email and all attachments are checked for viruses before use. No responsibility is accepted by Europe Incoming Ltd for any loss or damage arising in any way from receipt or use thereof. Europe Incoming Ltd is registered in England and Wales with no. 7053949. A list of directors is available at the registered office. Registered Office: Charterhouse (Accountants) Ltd, 166 College Road, Middlesex, HA1 1RA

**Comment by EIJason** [comment]
https://github.com/osTicket/osTicket/pull/5220

Apply this fix tooo

**Comment by Demarcation** [comment]
I'd support this change, as i run this locally myself.

**Pull request closed without merging**
