### PR TITLE
Fix for LDAP/AD auth plugin

### PR DESCRIPTION
**Pull request by ntozier**
removed:
87: ->annotate(array('__relevance__' => new SqlCode(1)))

This fixes Lookup Create new User Search on open ticket.

### CODE REVIEW

**Review by protich — APPROVED** [review]

**Comment by jdelhome3578** [comment]
@protich Should this filter case insensitive? I have some users where the email has some caps in AD but osTicket has all lower case.

**Comment by protich** [comment]
@jdelhome3578 - good question! As coded it will depend if MySQL is case-sensitive.

**Comment by kest874** [comment]
Confined working finally!

**Comment by mrdanne** [comment]
Did not work for me. Still same error 500

**Comment by ntozier** [comment]
@mrdanne then you do not have the same problem that we had.  Which is Search not working in with the LDAP/AD plugin enabled.

500 is a browser/server error which simply means "internal server error".  You will have to consult your PHP and/or Apache error logs to find out what the actual logged error is for us to be able to address it.

**Review by jdelhome3578 — APPROVED** [review]

**Comment by thedaftbadger** [comment]
Fix seems to search for the user now but doesn't actually populate the data required when selecting the found ldap entry.

**Comment by jdelhome3578** [comment]
@thedraftbadger Try #3441

**Comment by jdelhome3578** [comment]
@thedaftbadger try #3441

**Comment by thedaftbadger** [comment]
@jdelhome3578 Thanks, seems to add the info to the lookup form now 👍 will this still maintain the LDAP link for the user?

**Comment by jdelhome3578** [comment]
@thedaftbadger yes

**Comment by terrytibbles** [comment]
Any idea when this is going to get merged into an official version of osTicket?

**Comment by ntozier** [comment]
It's already been approved.
It is my understanding that will be included in the next release (1.11).

**Comment by jjjeroenski** [comment]
works for me also!

**Comment by alexkuc** [comment]
Any reason it is not merged despite being given green light?

**Comment by alexkuc** [comment]
@JediKev Oh, my bad! Guess I have missed that comment.

**Comment by ntozier** [comment]
Side note: this did not make it into 1.10.4.  I hear it is in 1.11-rc1 but haven't confirmed for myself.

**Pull request merged**
