### PR TITLE
Some text not translated fixed

### PR DESCRIPTION
**Pull request by Weibel73**
Some places fixed text.

### CODE REVIEW

**Comment by Chefkeks** [comment]
Just as a FYI:
This PR does include the fixes of #3651 (tickets.tmpl.php)
Nevertheless I'll keep #3651 open until this PR here or #3651 are merged.

**Comment by Weibel73** [comment]
@Chefkeks Hi!

I'm begginer on Git sorry if I make wrong. :(
I learn fast and try make better code for correct translating.

PR is Project or what?

Best regards
George

**Comment by Chefkeks** [comment]
Hi George,
no everything is fine, don't worry :) - it's just that I made a PR (yes = PullRequest) today in the morning to fix tickets.tmpl.php, which you fixed in this PR here too, so it's kinda duplicate, but sometimes the devs prefer to merge one PR instead of another PR and so I just mentioned it and will keep my PR open until one of them gets merged ;)

Great to see someone who is also working on improving the translations! I currently have a large PR, #3027 (if I remember correctly), to fix amd improve several translation related stuff.

That reminds me to ping the devs again since I'm still waiting for the answer of my question regarding the http status code translations.

Cheers,
Michael

**Comment by Weibel73** [comment]
Hi

I hunt many trans error and find about 15 this time 
I make PR to merge this :)

So im beginner and i have many simple question. Can youz contact me on Viber,Whatsapp,Skypeoreverthing else? :)

George

**Pull request closed without merging**
