### PR TITLE
Assign forms to tickets which are created by mail

### PR DESCRIPTION
**Pull request by gerundt**
Now should forms assigned to a ticket which created by mail. Of course are the values empty. Should fix one part of the bug #5846

### CODE REVIEW

**Comment by gerundt** [comment]
I create the new PR #6185 which has a option to enable the feature.

**Comment by JVC-MSF-OCB** [comment]
very nice!

how does this work with the latest versions?

**Comment by gerundt** [comment]
> very nice!
> 
> how does this work with the latest versions?

@JVC-MSF-OCB There is with #6185 a new version from the pull request, which should also work with the latest version.

**Comment by JVC-MSF-OCB** [comment]
Ok cool!

**Comment by johannarvaez-cmd** [comment]
Do you have this code for version 1.18?
I tried the one you shared and it didn't work.

**Pull request closed without merging**
