### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by PeopleInside**

### CODE REVIEW

**Review by PeopleInside — COMMENTED** [review]
Fix

**Comment by TechCare-Aus** [comment]
This is a good point.

**Comment by JediKev** [comment]
@PeopleInside @TechCare-Aus

Thank you for the pull request and comments. I would like to take a look at other projects' security files and see what we need to add.

Cheers.

**Comment by TechCare-Aus** [comment]
@JediKev - no drama mate. 

This world is becoming increasingly bent on stealing data and selling it. So I cannot stress enough how much we desperately need 2FA at the minimum.

#5568 #5538

**Comment by JediKev** [comment]
@TechCare-Aus

Yea, 2FA Login and OAuth2 support for email are the two main projects being worked on at the moment. Stay tuned.

Cheers.

**Comment by TechCare-Aus** [comment]
@JediKev 

That is brilliant to hear. Is it hard to add 2FA with Authenticator too? Or is that heaps more work? Forgive my lack of programming knowledge.

**Pull request merged**
