### PR TITLE
OAuth2 Resource Owner

### PR DESCRIPTION
**Pull request by protich**
This PR adds on changes made by @JediKev on PR #6466 by adding logic to Mail Protocol to support Shared / Aliased
mailboxes.

### CODE REVIEW

**Comment by protich** [comment]
PS: OAuth2 Plugin nolonger needs to mess with Resource Owner.

**Comment by MarcBanyard** [comment]
Just tested with the released version of the plugin and it works fine on sending and receiving emails on shared mailboxes.
The only bit that does not show (but I presume it is now no longer required) is the strict email matching.

Can this be pushed and published as the next version so people can start using it along with any possible plugin changes required for this?

**Comment by protich** [comment]
@MarcBanyard - We don't have a specific timeline. but we're in the process of preping it.

**Comment by protich** [comment]
PR rebased on top of `develop` branch.

**Pull request merged**
