### PR TITLE
Update scp.css - little more responsible frontend GUI - related to queues

### PR DESCRIPTION
**Pull request by mlipok**
Please cosider to add this changes to to the main code tree.
These changes made the interface finally more responsive, and it is possible to work on queues with many additional columns.

These are really small changes, but very powerful.

REMARK:
The change was made on my behalf by
https://useweb.pl/

### CODE REVIEW

**Comment by JediKev** [comment]
@mlipok 

Thank you for the pull request. We are doing a full UI/UX overhaul in v2.0. Please stay tuned.

Cheers.

**Comment by mlipok** [comment]
Do you have any roadmap ?
Could you publish them ?

**Comment by JediKev** [comment]
@mlipok 

We do not have a public roadmap at this time. We have been discussing making a public roadmap so one might be released in the future. Please stay tuned.

Cheers.

**Comment by mlipok** [comment]
@JediKev 
I know that there is TAG / LABEL  "Feature Request"
But could you create a special TAG / LABEL for "osTicket 2.x" which will give a way to sort out thing which are planed to do in "osTicket 2.x" ?

**Comment by mlipok** [comment]
For recent change take a look to my:
https://github.com/mlipok/osTicket/blob/develop/scp/css/scp.css

Related:
https://github.com/osTicket/osTicket/pull/5909
https://github.com/osTicket/osTicket/pull/5749
https://github.com/osTicket/osTicket/pull/3165
https://github.com/osTicket/osTicket/issues/3166

**Pull request closed without merging**
