### PR TITLE
replace alert window overlay `Unable to save draft. Refresh the curre…

### PR DESCRIPTION
**Pull request by ghost**
Fix for:
https://github.com/osTicket/osTicket-1.8/issues/2309

Replace alert window overlay `Unable to save draft. Refresh the current page to restore and continue your draft.` With a span status message that can be ignored by the user.

The new behavior is show in screenshot: http://i.imgur.com/4TAR3Gj.png

### CODE REVIEW

**Comment by ntozier** [comment]
Looks good.

**Comment by barrydegraaff** [comment]
Related issue:
https://github.com/osTicket/osTicket-1.8/issues/1189

**Comment by Chefkeks** [comment]
I like the idea to show the message there :+1:

**Comment by ghost** [comment]
No response from upstream.

**Pull request closed without merging**
