### PR TITLE
issue: Fix Most Redactor Issues

### PR DESCRIPTION
**Pull request by JediKev**
This addresses most Redactor issues we’ve been having lately (ie. Image
Paste, Bold button doesn’t work, etc.). This updates Redactor from 10.2.2
to 10.2.5 which seems to have resolved all the issues in testing. This
should not affect the original functionality but if you notice any strange
behaviors please let us know.

### CODE REVIEW

**Comment by CashDesk** [comment]
I installed it but unfortunateley we still get error messages like: 

[INSERT INTO `ost_attachment` SET `file_id` = 3316, `type` = 'D', `object_id` = 33393]

Duplicate entry '33393-3316-D' for key 'file-type'<br /> <br />
---- Backtrace ----<br />

**Comment by JediKev** [comment]
@CashDesk can you still paste the image though?

**Comment by CashDesk** [comment]
Yes after trying it a couple of times

**Comment by perryk** [comment]
Thanks @JediKev , I assume this replaces #3885 also ?

**Comment by JediKev** [comment]
@CashDesk Okay, sweet! I'll look into why it still throws the error.

@perryk Yes indeed! I needed people to test this one first to make sure I can close the other one lol

@Stoolbend That's great!

**Comment by CashDesk** [comment]
@JediKev Hi again, it looks like the canned response is not working anymore since the last change.

**Comment by JediKev** [comment]
@CashDesk Working just fine for me...what errors are you getting? Check your PHP/Apache error logs as well as your browser console (Network Tab) for AJAX errors.

**Comment by CashDesk** [comment]
@JediKev , Great Thanks!

**Comment by JediKev** [comment]
@CashDesk lol I update the pull as soon as you responded! Test these new changes and see if it works again! Cheers.

**Comment by CashDesk** [comment]
@JediKev , i installed the 2 files but unfortunately no canned  response.

**Comment by JediKev** [comment]
@CashDesk What browser are you using so I can try to replicate this.

**Comment by CashDesk** [comment]
Google Chrome

**Comment by JediKev** [comment]
Yea, after adding the one line in `scp/js/scp.js` I'm not able to replicate this on Chrome...it works perfectly in all of my browsers. I can confirm it's the line that fixes it because if I remove the line it doesn't work again. Try using the original file you had and just add that one line to the file. Cheers.

**Comment by CashDesk** [comment]
@JediKev , i download and installed the files again and it is working fine now, thanks again!

**Comment by JediKev** [comment]
@CashDesk Awesome! No problem! Cheers! 🍻

**Comment by Aka4Code** [comment]
Installed these changes and problem with image pasting `DB Error #1062` still exists:

```
[INSERT INTO `ost_attachment` SET `file_id` = 7073, `type` = 'D', `object_id` = 46325]

Duplicate entry '46325-7073-D' for key 'file-type'<br /> <br />
---- Wsteczne śledzenie ----<br />
#0 (główny katalog)/include/mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br />
#1 (główny katalog)/include/class.orm.php(3133): db_query('INSERT INTO `os...', true, true)<br />
#2 (główny katalog)/include/class.orm.php(597): MySqlExecutor->execute()<br />
#3 (główny katalog)/include/class.attachment.php(161): VerySimpleModel->save()<br />
#4 (główny katalog)/include/ajax.draft.php(101): GenericAttachments->upload(Array)<br />
#5 (główny katalog)/include/ajax.draft.php(300): DraftAjaxAPI->_uploadInlineImage(Object(Draft))<br />
#6 (główny katalog)/include/class.dispatcher.php(145): DraftAjaxAPI->uploadInlineImage('46325')<br />
#7 (główny katalog)/include/class.dispatcher.php(38): UrlMatcher->dispatch('46325/attach', Array)<br />
#8 (główny katalog)/include/class.dispatcher.php(120): Dispatcher->resolve('46325/attach', Array)<br />
#9 (główny katalog)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/draft/46325/at...', NULL)<br />
#10 (główny katalog)/scp/ajax.php(262): Dispatcher->resolve('/draft/46325/at...')<br />
#11 {main}
```

**Comment by Aka4Code** [comment]
@JediKev why you updated Redactor to outdated version `Redactor 10.2.5 Updated: October 1, 2015` while at the moment exists far brand new version of `Redactor II 2.12 updated DECEMBER 4, 2017` ?

If I will buy `Redactor II 2.12 updated DECEMBER 4, 2017` then can I replace osTicket Redactor version with it and it will work?

**Comment by mfelber** [comment]
Redactor II is not open source. 10.2.5 seems to be the latest version which was open source..

**Comment by JediKev** [comment]
@mfelber is correct. Also if you buy it the new code is COMPLETELY different then the old code so you'll have to rewrite everything...

**Comment by jdelhome3578** [comment]
@JediKev I am still getting the following error:
[INSERT INTO `ost_attachment` SET `file_id` = 536, `type` = 'D', `object_id` = 672]

Duplicate entry '672-536-D' for key 'file-type'<br /> <br />
---- Backtrace ----<br />
#0 C:\inetpub\osTicket\Live\include\mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')

#1 C:\inetpub\osTicket\Live\include\class.orm.php(3133): db_query('INSERT INTO `os...', true, true)<br />
#2 C:\inetpub\osTicket\Live\include\class.orm.php(597): MySqlExecutor->execute()<br />
#3 C:\inetpub\osTicket\Live\include\class.attachment.php(161): VerySimpleModel->save()<br />
#4 C:\inetpub\osTicket\Live\include\ajax.draft.php(101): GenericAttachments->upload(Array)<br />
#5 C:\inetpub\osTicket\Live\include\ajax.draft.php(300): DraftAjaxAPI->_uploadInlineImage(Object(Draft))<br />
#6 [internal function]: DraftAjaxAPI->uploadInlineImage('672')<br />
#7 C:\inetpub\osTicket\Live\include\class.dispatcher.php(145): call_user_func_array(Array, Array)<br />
#8 C:\inetpub\osTicket\Live\include\class.dispatcher.php(38): UrlMatcher->dispatch('672/attach', Array)<br />
#9 C:\inetpub\osTicket\Live\include\class.dispatcher.php(120): Dispatcher->resolve('672/attach', Array)<br />
#10 C:\inetpub\osTicket\Live\include\class.dispatcher.php(38): UrlMatcher->dispatch('/draft/672/atta...', NULL)<br />
#11 C:\inetpub\osTicket\Live\scp\ajax.php(262): Dispatcher->resolve('/draft/672/atta...')<br />
#12 {main}

**Comment by ntozier** [comment]
Have you gone into the DB and erased the duplicate?

**Comment by JediKev** [comment]
@jdelhome3578 I haven't been able to reproduce this at all but from what you just described it would appear so. Maybe Redactor isn't catching the changes? Try typing some stuff after the image to update the Draft and see if Redactor has the image. Also, try switching to HMTL view and see if you see the image tag in it with references to the image.

**Comment by jdelhome3578** [comment]
@JediKev the only way I could reproduce the error was to paste the image on a new line. I tried your suggestion on typing after the past and that did not work. Also, there was no image tag.

**Comment by MrAnonymouse** [comment]
I tried this with osTicket (v1.10.1) only to find it didn't help... thanks anyway.  I've had the issue for a very long time and I find trying to paste something 2-3 times sometimes will get it to showup and I always get spammed errors in my email.

**Comment by JediKev** [comment]
@MrAnonymouse

Yea, upon further testing it didn’t help that much so we are addressing this in a _totatly_ different way after v1.11 is released.

Thanks for the feedback. Cheers.

**Comment by perryk** [comment]
Just a heads up this is conflicting with #4389 .

**Comment by JediKev** [comment]
@perryk

Thanks! We are dropping this pull in favor of the old one (3885) as this broke some things like custom Redactor plugins.

Cheers.

**Comment by JediKev** [comment]
Closing this pull in favor of the new one:
https://github.com/osTicket/osTicket/pull/4464

God help us all....

**Pull request closed without merging**
