### PR TITLE
Hyperlinks with port numbers not generating correctly

### PR DESCRIPTION
**Pull request by Chefkeks**
Create this PR on behalf of osTicket forum user Luis_PvxPlus.
For more details take a look here: http://osticket.com/forum/discussion/87001/hyperlinks-with-port-numbers-not-generating-correctly

Have NOT tested it myself!

### CODE REVIEW

**Comment by greezybacon** [comment]
@Chefkeks could you rebase this against the `develop` branch

**Comment by Chefkeks** [comment]
Sure, will do tomorrow :)

**Comment by Chefkeks** [comment]
@greezybacon 
See https://github.com/osTicket/osTicket-1.8/pull/2813 for rebased PR against `develop` branch.

**Comment by greezybacon** [comment]
Closed in favor of #2813

**Pull request closed without merging**
