### PR TITLE
redactor: Upgrade to version 3.4.4

### PR DESCRIPTION
**Pull request by JediKev**
This upgrades Redactor from `3.4.2` to `3.4.3` then again to `3.4.4` so that we are utilizing the latest code. This provides a few bug fixes and improvements.

### CODE REVIEW

**Comment by TechCare-Aus** [comment]
@JediKev - can we please get this applied to the main develop branch?

**Comment by JediKev** [comment]
@TechCare-Aus 

The way our pull requests work is we make the pull, then our team and the community can pull/test the changes, and once confirmed/approved it will be merged.

Cheers.

**Comment by TechCare-Aus** [comment]
@JediKev - totally fine with that. Can you advise how to apply this particular PR so that I can test and provide feedback? I'm not great at the whole git thing. I know it can do this, but how is the problem. Sorry.

**Comment by JediKev** [comment]
Updated to `3.4.4` - **Released October 6th, 2020**

**Pull request merged**
