### PR TITLE
faq: Fix crash rendering list of categories

### LINKED ISSUE #3147: Fatal error  Call to a member function sort() on array
On **develop**, the page https://example.com/scp/kb.php gives
`Fatal error: Call to a member function sort() on array in /root_path/include/staff/faq-categories.inc.php on line 148`

I use a workaround like this:

```
- $categories->sort(function($a) { return $a->getLocalName(); });
```

```
+ sort($categories);
```

but I don't think it is the better way

Here is the config:
- osticket develop
- Debian Jessie
- Nginx

### PR DESCRIPTION
**Pull request by greezybacon**
Fixes #3147

### CODE REVIEW

**Comment by rbukovansky** [comment]
So, if my understanding is correct I can patch my osTicket installation with this and remove the changes I've made in #3096 ?

**Comment by greezybacon** [comment]
@rbukovansky yes. This patch is a more direct fix

**Comment by crypticmind** [comment]
FWIW 👍

**Comment by jdelhome3578** [comment]
Already fixed with 624a4b0

**Comment by rayfoss** [comment]
@jdelhome3578 thanks for the catch.

**Pull request closed without merging**
