### PR TITLE
fix staff login redirect loop when system is offline

### PR DESCRIPTION
**Pull request by cengizonkal**
When the system is offline, it goes into an infinite loop when the staff tries to log in. 
With this fix, if the system is offline, authenticated user logs out before redirecting to the login page.

### CODE REVIEW

**Review by JediKev — COMMENTED** [review]
Thank you for the pull and a summary of the issue. We are going to review this change.

**Comment by JediKev** [comment]
Needs rebase

**Comment by cengizonkal** [comment]
> Needs rebase

Done.

**Comment by JediKev** [comment]
@cengizonkal 

Sorry, I should've been more clear; I left the comment for myself lol Anyways, this needs to be rebased to `1.15.x` branch.

Cheers.

**Comment by cengizonkal** [comment]
No problem. Do you require anything from me. Should i do something?

**Comment by JediKev** [comment]
@cengizonkal 

Yes, I just rebased on Github but as you can see it included a ton of extra commits from `develop`. So, from here you need to rebase to `1.15.x` locally and push to Github to update this pull.

Cheers.

**Comment by cengizonkal** [comment]
> @cengizonkal
> 
> Yes, I just rebased on Github but as you can see it included a ton of extra commits from `develop`. So, from here you need to rebase to `1.15.x` locally and push to Github to update this pull.
> 
> Cheers.

I think it's ok now. Sorry for inconvenience.

**Pull request merged**
