### PR TITLE
Introducing Schedules / Business Hours for SLAs (upgrade required)

### PR DESCRIPTION
**Pull request by protich**
Business Hours SLA has been the most requested feature for years - we've had some implementations from the community but none felt like a good & extensible implementation, at least to me anyhow. This is not perfect either but it's a good start... play with it and let us know what we missed.

--

Schedules are collection of date-time entries that can be used to specify when SLAs are active - by defining Business Hours (working hours) and Holidays (holiday hours). For example, if an SLA is set to 8-5 Weekdays schedule, the SLA Grace Period only counts time during those hours with holidays (if any) taken into account.

Here are some screenshots for the curious.

* Schedules can be Managed in Admin Panel > Manage > Schedules
Screen Shot 2019-08-12 at 11 58 56 AM

* Adding a new Schedule - Possible types are 1) Business Hours and 2) Holiday Hours
Screen Shot 2019-08-12 at 12 01 23 PM

* A Schedule can have unlimited _Date /Time Entries_. Business Hours schedules can apply one or multiple Holidays.

Screen Shot 2019-08-12 at 11 59 25 AM

* Entries can repeat on desired frequency and date / time - think calendar. 
Screen Shot 2019-08-12 at 12 00 22 PM

* Here is an example of U.S. Holiday entries 
Screen Shot 2019-08-12 at 11 59 52 AM

* Business Hours Schedules come with handy Timeline Diagnostic debugging tool to show you how working hours and holidays are applied. 
Screen Shot 2019-08-12 at 12 00 48 PM

That's great, but how do you actually use the feature?  It's simple simply attach a schedule to an SLA, Department or configure a system default.

* System Default -> Admin Panel > Settings > System > Date & Time Options
Screen Shot 2019-08-12 at 12 28 25 PM

* Department Schedule -> Admin Panel > Agents > Departments > Department
Screen Shot 2019-08-12 at 12 29 47 PM

* SLA Schedule -> Admin Panel > Manage > SLAs > SLA
Screen Shot 2019-08-12 at 12 28 59 PM

Department's Schedule takes precedence (think regional support hours), then SLAs specific and lastly System Schedule is used as the default.

The feature / PR will trigger an upgrade - so make sure you do it in dev environment or simply do a new install.

### CODE REVIEW

**Comment by mlipok** [comment]
I see this looking promising.
This is still beta ?
How I can test this ?

**Comment by JediKev** [comment]
@mlipok 

Go to pull request, click the branch name of the submitter, then click Clone or Download and download as ZIP. Or you can utilize Github's API for ZIP file:
- https://api.github.com/repos/osTicket/osTicket/zipball/pull/4984/head

**Note:**
This requires an upgrade so don't do this in production.

Cheers.

**Comment by mlipok** [comment]
How  Schedule and Entries, are related each toogether ?

**Comment by protich** [comment]
> How Schedule and Entries, are related each toogether ?

Entries are dates / times that make up the Schedule. Think of Schedule as a container - For example, "8-5 Workdays" Schedule will have an entry for 8am-5pm entry  repeated weekly on workdays or Individual days Mon-Frid as entries.

**Comment by mlipok** [comment]
Ok.
I just post email to my web-admin to create me separate beta testing osTicket installation.
Will take a look when I back from my vacation... soon :(

**Comment by apracz** [comment]
> * https://api.github.com/repos/osTicket/osTicket

i download the file and upload to mysql server using a devel database, 
my actual version is osTicket (v1.10.1), after upload the files this error show 

Warning: file_exists(): Unable to find the wrapper "phar" - did you forget to enable it when you configured PHP? in /home/rpsolution/rpsolution/sup2/suporte/include/class.translation.php on line 738

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/rpsolution/rpsolution/sup2/suporte/include/class.translation.php:738) in /home/rpsolution/rpsolution/sup2/suporte/include/class.ostsession.php on line 86

Warning: Cannot modify header information - headers already sent by (output started at /home/rpsolution/rpsolution/sup2/suporte/include/class.translation.php:738) in /home/rpsolution/rpsolution/sup2/suporte/include/class.ostsession.php on line 109

Warning: Cannot modify header information - headers already sent by (output started at /home/rpsolution/rpsolution/sup2/suporte/include/class.translation.php:738) in /home/rpsolution/rpsolution/sup2/suporte/include/staff/header.inc.php on line 2

Warning: Cannot modify header information - headers already sent by (output started at /home/rpsolution/rpsolution/sup2/suporte/include/class.translation.php:738) in /home/rpsolution/rpsolution/sup2/suporte/include/staff/header.inc.php on line 3

**Comment by JediKev** [comment]
@apracz 

🤦‍♂ This is intended to go on top of `1.12.x` not `1.10.x`. You will need to upgrade to v1.12.2 or create a test install of v1.12.2 in order to test this feature.

Cheers.

**Comment by DevOpsRnD** [comment]
Hi is there any feature of Pause and Resume Tickets Which already have SLA

**Comment by Richiricheh** [comment]
I have mentioned this for a while. Please add me as a +1 for this.

**Comment by rolltidehero** [comment]
What version is this feature available in?

**Comment by ntozier** [comment]
It was merged into osTicket:develop-next on Sep 5, 2019.  So any version released after that.

**Pull request merged**
