### PR TITLE
Fix first problems with PHP 8

### PR DESCRIPTION
**Pull request by gerundt**
I used [Phan](https://github.com/phan/phan) to check the osTicket source code for problems with **PHP 8**.

This fixes are only the tip of the iceberg, but I want to know first if you accepts this type of pull requests before I do more work. 😉

### CODE REVIEW

**Comment by stefanhuber** [comment]
Please accept these changes!

**Comment by JediKev** [comment]
@stefanhuber We will be looking at PHP 8 support soon.

**Comment by ChrisTG742** [comment]
Wow, I never knew that using curly braces were allowed as indices. Haven't seen this before in any other PHP code snippet yet.

**Comment by stefanhuber** [comment]
@ChrisTG742 also calling object methods like static class methods is rather strange. Crazy enough that it was possible until php 8...

**Comment by JediKev** [comment]
@gerundt 

We have put together a [Release Candidate here](https://forum.osticket.com/d/100256-php-8-support-v1155-rc1-pre-release) (labeled `v1.15.5-rc1`) that includes this pull request and other changes to support PHP 8. We ask that the community tests this RC and give us feedback on any further issues with PHP 8.

**Note:**
This package requires PHP 8 and is a Release Candidate that should _not_ be used in production.

Cheers.

**Comment by juddm** [comment]
I migrated 1.15.2 to 1.15.5-rc1 today.  All went smoothly except for the plugins. I disabled the existing plugins (might be good to automate this in the upgrade script) and then alert the user at the end of the upgrade process.  I did find the updated ldap plugin works, but no joy with file system attachments, audit, or google 2fa.  I haven't tried building the plugins but can do so and test if this helps.

**Comment by JediKev** [comment]
@juddm 

Thank you for this information. We will test the FS, audit, and google 2fa plugins to see what's going on. Any further feedback is welcome.

Cheers.

**Comment by JediKev** [comment]
This was merged as part of `1.16.x`.

**Pull request closed without merging**
